[package]
name = "tmxr-command"
description = "tmux-compatible command language for tmxr: parser, key names and formats."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
readme.workspace = true

[dependencies]
crossterm = "0.29.0"
regex = "1.13.1"
thiserror = "2.0.21"

[lints]
workspace = true
