name: Cron

on:
  schedule:
    - cron: '0 6 * * 1' # Monday 06:00 UTC
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deny:
    name: cargo-deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny
      - run: cargo deny --all-features check
